### ISSUE TITLE
Should one example be targetting the UKB data provider ?

### ISSUE THREAD

**Issue by jbpoline** [neurohub/neurohub_examples#2]
At the moment, we dont see in the example what is the content of the data provider, I think we could have an example with the specific UKB data provider (and then plug a simple ML as a demonstration of how to use these files?)

**Comment by dlq** [comment]
A basic example showing access to NeuroHub with the CBRAIN API is a good start but - yes, there should be a separate example for basic neuro imaging and one for ML.

**Comment by dlq** [comment]
I've opened separate issues for each of the points you bring up.
